import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import Page from "@/components/Page/Page";

const kumbh = Kumbh_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={kumbh.className}>
        <Page>
          {children}
        </Page>
      </body>
    </html>
  );
}
